# Generated by Django 3.0.5 on 2023-11-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=120)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
