# Generated by Django 5.0.2 on 2024-07-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
