# Generated by Django 3.0.5 on 2023-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
