# Generated by Django 5.0.2 on 2024-07-31 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog1',
        ),
    ]
