# Generated by Django 5.0.2 on 2024-07-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_blog1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='chead0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog1',
            name='chead1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog1',
            name='chead2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
