# Generated by Django 5.0.2 on 2024-08-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_simpleblog1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleblog1',
            old_name='post_id',
            new_name='sno',
        ),
    ]
